version: '3.9'

services:
  
  db:
    image: postgres:latest
    restart: always
    container_name: fast_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=kefir_api
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    depends_on:
      - db
    build: fastapi/
    restart: always
    container_name: api
    environment:
      - DB_URL=db
      - DB=kefir_api
    ports:
      - 3112:8000
    
    
    command: uvicorn run:app --host 0.0.0.0 --port 8000